// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnzekydbshcenxadvcib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuemVreWRic2hjZW54YWR2Y2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDc1MTAsImV4cCI6MjA1ODQyMzUxMH0.hxyw7sv54E2Qlr4O6WdYE5wPW9SztZRMV4ricHNtihI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);